# Generated by Django 5.1.1 on 2024-09-26 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('comp_code', models.AutoField(primary_key=True, serialize=False)),
                ('comp_name', models.CharField(max_length=255)),
                ('comp_location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='branch',
            fields=[
                ('branch_code', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=255)),
                ('comp_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('emp_email', models.EmailField(max_length=254, unique=True)),
                ('emp_doj', models.DateField()),
                ('emp_dept', models.CharField(blank=True, choices=[('HR', 'Human Resources'), ('FIN', 'Finance'), ('DEV', 'Developers'), ('DES', 'Design')], max_length=3, null=True)),
                ('branch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.branch')),
                ('comp_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company')),
            ],
        ),
    ]
