# Generated by Django 5.1.1 on 2024-09-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='comp_code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
